arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 15000
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 3000
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1


hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_index_RT
    - joint_index_MCP
    - joint_index_PIP
    - joint_index_DIP
    - joint_middle_RT
    - joint_middle_MCP
    - joint_middle_PIP
    - joint_middle_DIP
    - joint_ring_RT
    - joint_ring_MCP
    - joint_ring_PIP
    - joint_ring_DIP
    - joint_pinky_RT
    - joint_pinky_MCP
    - joint_pinky_PIP
    - joint_pinky_DIP
    - joint_thumb_CMC_1
    - joint_thumb_CMC_2
    - joint_thumb_MP
    - joint_thumb_IP

  gains:
    joint_index_RT:    {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_index_MCP:   {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_index_PIP:   {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_index_DIP:   {p: 10, d: 1, i: 1, i_clamp: 1}

    joint_middle_RT:   {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_middle_MCP:  {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_middle_PIP:  {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_middle_DIP:  {p: 10, d: 1, i: 1, i_clamp: 1}

    joint_ring_RT:     {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_ring_MCP:    {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_ring_PIP:    {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_ring_DIP:    {p: 10, d: 1, i: 1, i_clamp: 1}

    joint_pinky_RT:    {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_pinky_MCP:   {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_pinky_PIP:   {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_pinky_DIP:   {p: 10, d: 1, i: 1, i_clamp: 1}

    joint_thumb_CMC_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_thumb_CMC_2: {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_thumb_MP:    {p: 10, d: 1, i: 1, i_clamp: 1}
    joint_thumb_IP:    {p: 10, d: 1, i: 1, i_clamp: 1}